# Generated by Django 3.0.7 on 2020-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advocate_First_Name', models.CharField(max_length=200)),
                ('Advocate_Last_Name', models.CharField(max_length=200)),
                ('Advocate_Email', models.CharField(max_length=200)),
                ('Friend_First_Name', models.CharField(max_length=200)),
                ('Friend_Last_Name', models.CharField(max_length=200)),
                ('Friend_Email', models.CharField(max_length=200)),
                ('Order_Number', models.CharField(max_length=200)),
                ('Completed_At', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200)),
                ('Total_Amount_Spent', models.DecimalField(decimal_places=2, max_digits=999)),
            ],
        ),
    ]
