# Generated by Django 3.0.7 on 2020-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_auto_20200721_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='Completed_At',
            field=models.DateField(blank=True, null=True),
        ),
    ]
